function y = ElementStiffness3(he,E,A,lx,ly)
    y = [(A*E*lx^2)/he,  (A*E*lx*ly)/he,  -(A*E*lx^2)/he, -(A*E*lx*ly)/he;...
        (A*E*lx*ly)/he,(A*E*ly^2)/he, -(A*E*lx*ly)/he,  -(A*E*ly^2)/he;...
        -(A*E*lx^2)/he, -(A*E*lx*ly)/he,   (A*E*lx^2)/he,  (A*E*lx*ly)/he;...
        -(A*E*lx*ly)/he,  -(A*E*ly^2)/he,  (A*E*lx*ly)/he,   (A*E*ly^2)/he];

